#!/bin/bash

OLD=$(cat /sys/kernel/fast_charge/force_fast_charge)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 		Fast Charge Toggle              +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Setting: $OLD"
echo "1) Enable Fast Charge"
echo "2) Disable Fast Charge"
echo "R) Return to Main Menu"
echo "X) Exit"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) echo "1" > /sys/kernel/fast_charge/force_fast_charge && echo "Fast Charge Enabled" && sh popcorn_fc;;
      2) echo "0" > /sys/kernel/fast_charge/force_fast_charge && echo "Fast Charge Disabled" && sh popcorn_fc;;
      R) sh popcorn;;
      x) exit 1;;
      *) echo "Invalid option" && sh popcorn_fc;;

    esac
  fi

