#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+             Touch Wake Params                   +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "State Delay Time (this number should be a numerical value---default is 45000, 0=indefinate"
echo "Or press R Return to TouchWake Menu or X to Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      $opt) echo "$opt" > /sys/class/misc/touchwake/delay && echo "Your Touch Wake delay value is $opt" && sh popcorn_tw1;;
      R) sh popcorn_tw;;
      X) exit 1;;
 
    esac
  fi

