#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 	         Color Control                  +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "1) Omap Gamma Control"
echo "2) Gamma Offsets"
echo "3) Color Multipliers"
echo "R) Return to Menu Script"
echo "X) Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) sh popcorn_cc1;;
      2) sh popcorn_cc2;;
      3) sh popcorn_cc3;;
      R) sh popcorn;;
      X) exit 1;;
      *) echo "Invalid option" && sh popcorn_cc;;
     
    esac
  fi

