#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 		Smart Reflex Toggle             +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "1) Enable SmartReflex for MPU"
echo "2) Disable SmartReflex for MPU"
echo "3) Enable SmartReflex for IVA"
echo "4) Disable SmartReflex for IVA"
echo "5) Enable SmartReflex for Core (GPU)"
echo "6) Disable SmartReflex for Core (GPU)"
echo "R) Return to Main Menu"
echo "X) Exit"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) echo "1" > /sys/kernel/debug/smartreflex/sr_mpu/autocomp && echo "SmartReflex for MPU is ENABLED" && sh popcorn_sr;;
      2) echo "0" > /sys/kernel/debug/smartreflex/sr_mpu/autocomp && echo "SmartReflex for MPU is DISABLED" && sh popcorn_sr;;
      3) echo "1" > /sys/kernel/debug/smartreflex/sr_iva/autocomp && echo "SmartReflex for IVA is ENABLED" && sh popcorn_sr;;
      4) echo "0" > /sys/kernel/debug/smartreflex/sr_iva/autocomp && echo "SmartReflex for IVA is DISABLED" && sh popcorn_sr;;
      5) echo "1" > /sys/kernel/debug/smartreflex/sr_core/autocomp && echo "SmartReflex for CORE is ENABLED" && sh popcorn_sr;;
      6) echo "0" > /sys/kernel/debug/smartreflex/sr_core/autocomp && echo "SmartReflex for CORE is DISABLED" && sh popcorn_sr;;
      R) sh popcorn;;
      X) exit 1;;
    esac
  fi

