#!/system/bin/sh
mount -o remount,rw,noatime,nodiratime -t ext3 /dev/block/mmcblk0p25 /system
initPath=/system/etc/init.d/99sonic
OLD=$(cat /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 	       Voltage Control                  +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Voltages: $OLD"
echo "Enter your voltages below. Press B to set on boot, R to return to main menu, or X to Exit"
echo "NOTE: YOU MUST ENTER VOLTAGES EXACTLY THE WAY THEY ARE IN THE CURRENT VOLTAGES PROMPT (IE: 230mhz: 850mV)"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      B) sed -i "s|^uV=.*|uV=$OLD|" $initPath && echo "Settings set on boot" && sleep 2 && sh /system/xbin/popcorn_volt;;
      R) sh /system/xbin/popcorn;;
      X) exit 1;;
     $opt) echo "$opt" > /sys/class/misc/colorcontrol/v1_offset && echo "Voltages set at $opt" && sleep 2 && sh /system/xbin/popcorn_volt;;
     
    esac
  fi

