#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 	         Color Control                  +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "1) Omap Color Control"
echo "2) V1 Offsets"
echo "3) Color Multipliers"
echo "R) Return to Menu Script"
echo "X) Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) su && sh popcorn_cc1;;
      2) su && sh popcorn_cc2;;
      3) su && sh popcorn_cc3;;
      R) sh popcorn;;
      X) exit 1;;
     
    esac
  fi

