#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ Welcome to the PopcornKernel Customizer utility +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "1) SmartReflex Toggle"
echo "2) GPU Overclock"
echo "3) BLX Params"
echo "4) Touch Wake Toggle/Params"
echo "5) Fast Charge Toggle"
echo "6) Wifi Low-Latency Toggle"
echo "7) Color Control"
echo "8) Sound Control"
echo "X) Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) sh popcorn_sr;;
      2) sh popcorn_gpu;;
      3) sh popcorn_blx;;
      4) sh popcorn_tw;;
      5) sh popcorn_fc;;
      6) sh popcorn_wll;;
      7) sh popcorn_cc;;
      8) sh popcorn_sc;;
      X) echo "Goodbye."; echo; exit 1;;
      *) echo "Invalid option";;
    esac
  fi

