#!/bin/bash

OLD=$(cat /sys/class/misc/touchwake/delay)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+             Touch Wake Params                   +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Delay Time: $OLD"
echo "State Delay Time (this number should be a numerical value---default is 45000"
echo "Or press R to return to TouchWake Menu or X to Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      R) sh popcorn_tw;;
      X) exit 1;;
      $opt) echo "$opt" > /sys/class/misc/touchwake/delay && echo "Your Touch Wake delay value is $opt" && sh popcorn_tw1;;

    esac
  fi

