#!/system/bin/sh
mount -o remount,rw,noatime,nodiratime -t ext3 /dev/block/mmcblk0p25 /system
initPath=/system/etc/init.d/99sonic
OLDSAFE=$(cat /sys/class/misc/colorcontrol/safety_enabled)
OLDMULT=$(cat /sys/class/misc/colorcontrol/multiplier)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 	      Color Multipliers                 +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Settings: Safety = $OLDSAFE"
echo "Multipliers = $OLDMULT"
echo "1) Enable Safety Feature"
echo "2) Disable Safety Feature"
echo 
echo "Or pick your multipliers. Recomended values are 1604318000 1614318000 2234318000"
echo "Press B to set the current settings on boot"
echo "Press R to return to Main Color Control script or press X to exit script"
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
   1) echo "1" > /sys/class/misc/colorcontrol/safety_enabled && echo "Color Multipliers Safety Enabled" && sleep 2 && sh /system/xbin/popcorn_cc3;;
   2)   echo "0" > /sys/class/misc/colorcontrol/safety_enabled && echo "Color Multipliers Safety Disabled" && sleep 2 && sh /system/xbin/popcorn_cc3;;
   B) busybox sed -i "s|^ColorSafety=.*|ColorSafety=$OLDSAFE|" $initPath && busybox sed -i "s|^ColorMult=.*|ColorMult=$OLDMULT|" $initPath && echo "Settings set on boot" && sleep 2 && sh /system/xbin/popcorn_cc3;;
   R) sh /system/xbin/popcorn_cc;;
   X) exit 1;;
  $opt) echo "$opt" > /sys/class/misc/colorcontrol/multiplier && echo "Color Multipliers Set at $opt" && sleep 2 && sh /system/xbin/popcorn_cc3;;
  
    esac
  fi

