#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 		BLX Parameters                  +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Please pick a BLX Value between 1-100 (DEFAULT 100)"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      0) echo "0" > /sys/class/misc/batterylifeextender/charging_limit;;
      1) echo "1" > /sys/class/misc/batterylifeextender/charging_limit;;
      2) echo "2" > /sys/class/misc/batterylifeextender/charging_limit;;
      3) echo "3" > /sys/class/misc/batterylifeextender/charging_limit;;
      4) echo "4" > /sys/class/misc/batterylifeextender/charging_limit;;
      5) echo "5" > /sys/class/misc/batterylifeextender/charging_limit;;
      6) echo "6" > /sys/class/misc/batterylifeextender/charging_limit;;
      7) echo "7" > /sys/class/misc/batterylifeextender/charging_limit;;
      8) echo "8" > /sys/class/misc/batterylifeextender/charging_limit;;
      9) echo "9" > /sys/class/misc/batterylifeextender/charging_limit;;
      10) echo "10" > /sys/class/misc/batterylifeextender/charging_limit;;
      11) echo "11" > /sys/class/misc/batterylifeextender/charging_limit;;
      12) echo "12" > /sys/class/misc/batterylifeextender/charging_limit;;
      13) echo "13" > /sys/class/misc/batterylifeextender/charging_limit;;
      14) echo "14" > /sys/class/misc/batterylifeextender/charging_limit;;
      15) echo "15" > /sys/class/misc/batterylifeextender/charging_limit;;
      16) echo "16" > /sys/class/misc/batterylifeextender/charging_limit;;
      17) echo "17" > /sys/class/misc/batterylifeextender/charging_limit;;
      18) echo "18" > /sys/class/misc/batterylifeextender/charging_limit;;
      19) echo "19" > /sys/class/misc/batterylifeextender/charging_limit;;
      20) echo "20" > /sys/class/misc/batterylifeextender/charging_limit;;
      21) echo "21" > /sys/class/misc/batterylifeextender/charging_limit;;
      22) echo "22" > /sys/class/misc/batterylifeextender/charging_limit;;
      23) echo "23" > /sys/class/misc/batterylifeextender/charging_limit;;
      24) echo "24" > /sys/class/misc/batterylifeextender/charging_limit;;
      25) echo "25" > /sys/class/misc/batterylifeextender/charging_limit;;
      26) echo "26" > /sys/class/misc/batterylifeextender/charging_limit;;
      27) echo "27" > /sys/class/misc/batterylifeextender/charging_limit;;
      28) echo "28" > /sys/class/misc/batterylifeextender/charging_limit;;
      29) echo "29" > /sys/class/misc/batterylifeextender/charging_limit;;
      30) echo "30" > /sys/class/misc/batterylifeextender/charging_limit;;
      31) echo "31" > /sys/class/misc/batterylifeextender/charging_limit;;
      32) echo "32" > /sys/class/misc/batterylifeextender/charging_limit;;
      33) echo "33" > /sys/class/misc/batterylifeextender/charging_limit;;
      34) echo "34" > /sys/class/misc/batterylifeextender/charging_limit;;
      35) echo "35" > /sys/class/misc/batterylifeextender/charging_limit;;
      36) echo "36" > /sys/class/misc/batterylifeextender/charging_limit;;
      37) echo "37" > /sys/class/misc/batterylifeextender/charging_limit;;
      38) echo "38" > /sys/class/misc/batterylifeextender/charging_limit;;
      39) echo "39" > /sys/class/misc/batterylifeextender/charging_limit;;
      40) echo "40" > /sys/class/misc/batterylifeextender/charging_limit;;
      41) echo "41" > /sys/class/misc/batterylifeextender/charging_limit;;
      42) echo "42" > /sys/class/misc/batterylifeextender/charging_limit;;
      43) echo "43" > /sys/class/misc/batterylifeextender/charging_limit;;
      44) echo "44" > /sys/class/misc/batterylifeextender/charging_limit;;
      45) echo "45" > /sys/class/misc/batterylifeextender/charging_limit;;
      46) echo "46" > /sys/class/misc/batterylifeextender/charging_limit;;
      47) echo "47" > /sys/class/misc/batterylifeextender/charging_limit;;
      48) echo "48" > /sys/class/misc/batterylifeextender/charging_limit;;
      49) echo "49" > /sys/class/misc/batterylifeextender/charging_limit;;
      50) echo "50" > /sys/class/misc/batterylifeextender/charging_limit;;
      51) echo "51" > /sys/class/misc/batterylifeextender/charging_limit;;
      52) echo "52" > /sys/class/misc/batterylifeextender/charging_limit;;
      53) echo "53" > /sys/class/misc/batterylifeextender/charging_limit;;
      54) echo "54" > /sys/class/misc/batterylifeextender/charging_limit;;
      55) echo "55" > /sys/class/misc/batterylifeextender/charging_limit;;
      56) echo "56" > /sys/class/misc/batterylifeextender/charging_limit;;
      57) echo "57" > /sys/class/misc/batterylifeextender/charging_limit;;
      58) echo "58" > /sys/class/misc/batterylifeextender/charging_limit;;
      59) echo "59" > /sys/class/misc/batterylifeextender/charging_limit;;
      60) echo "60" > /sys/class/misc/batterylifeextender/charging_limit;;
      61) echo "61" > /sys/class/misc/batterylifeextender/charging_limit;;
      62) echo "62" > /sys/class/misc/batterylifeextender/charging_limit;;
      63) echo "63" > /sys/class/misc/batterylifeextender/charging_limit;;
      64) echo "64" > /sys/class/misc/batterylifeextender/charging_limit;;
      65) echo "65" > /sys/class/misc/batterylifeextender/charging_limit;;
      66) echo "66" > /sys/class/misc/batterylifeextender/charging_limit;;
      67) echo "67" > /sys/class/misc/batterylifeextender/charging_limit;;
      68) echo "68" > /sys/class/misc/batterylifeextender/charging_limit;;
      69) echo "69" > /sys/class/misc/batterylifeextender/charging_limit;;
      70) echo "70" > /sys/class/misc/batterylifeextender/charging_limit;;
      71) echo "71" > /sys/class/misc/batterylifeextender/charging_limit;;
      72) echo "72" > /sys/class/misc/batterylifeextender/charging_limit;;
      73) echo "73" > /sys/class/misc/batterylifeextender/charging_limit;;
      74) echo "74" > /sys/class/misc/batterylifeextender/charging_limit;;
      75) echo "75" > /sys/class/misc/batterylifeextender/charging_limit;;
      76) echo "76" > /sys/class/misc/batterylifeextender/charging_limit;;
      77) echo "77" > /sys/class/misc/batterylifeextender/charging_limit;;
      78) echo "78" > /sys/class/misc/batterylifeextender/charging_limit;;
      79) echo "79" > /sys/class/misc/batterylifeextender/charging_limit;;
      80) echo "80" > /sys/class/misc/batterylifeextender/charging_limit;;
      81) echo "81" > /sys/class/misc/batterylifeextender/charging_limit;;
      82) echo "82" > /sys/class/misc/batterylifeextender/charging_limit;;
      83) echo "83" > /sys/class/misc/batterylifeextender/charging_limit;;
      84) echo "84" > /sys/class/misc/batterylifeextender/charging_limit;;
      85) echo "85" > /sys/class/misc/batterylifeextender/charging_limit;;
      86) echo "86" > /sys/class/misc/batterylifeextender/charging_limit;;
      87) echo "87" > /sys/class/misc/batterylifeextender/charging_limit;;
      88) echo "88" > /sys/class/misc/batterylifeextender/charging_limit;;
      89) echo "89" > /sys/class/misc/batterylifeextender/charging_limit;;
      90) echo "90" > /sys/class/misc/batterylifeextender/charging_limit;;
      91) echo "91" > /sys/class/misc/batterylifeextender/charging_limit;;
      92) echo "92" > /sys/class/misc/batterylifeextender/charging_limit;;
      93) echo "93" > /sys/class/misc/batterylifeextender/charging_limit;;
      94) echo "94" > /sys/class/misc/batterylifeextender/charging_limit;;
      95) echo "95" > /sys/class/misc/batterylifeextender/charging_limit;;
      96) echo "96" > /sys/class/misc/batterylifeextender/charging_limit;;
      97) echo "97" > /sys/class/misc/batterylifeextender/charging_limit;;
      98) echo "98" > /sys/class/misc/batterylifeextender/charging_limit;;
      99) echo "99" > /sys/class/misc/batterylifeextender/charging_limit;;
      100) echo "100" > /sys/class/misc/batterylifeextender/charging_limit;;
    esac
  fi

