#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 		GPU Overclock                   +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Overclock GPU to the following preset values:"
echo "0) 307MHz--default"
echo "1) 384MHz"
echo "2) 460MHz"
echo "3) 512MHz"
echo "R) Return to Main Menu"
echo "X) Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      0) echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 307 MHz" && sh popcorn_gpu;;
      1) echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 384 MHz" && sh popcorn_gpu;;
      2) echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 460 MHz" && sh popcorn_gpu;;
      3) echo "3" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc && echo "GPU Now Clocked at 512 MHz" && sh popcorn_gpu;;
      R) sh popcorn;;
      X) exit 1;;
      *) echo "Invalid option" && sh popcorn_gpu;;
    esac
  fi

