#!/bin/bash

OLD=$(cat /sys/class/misc/touchwake/enabled
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+             Touch Wake Toggle                   +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Status of TouchWake: $OLD"
echo "1) Toggle Touch Wake (0=off 1=on)"
echo "2) Touch Wake Params"
echo "R) Return to Main Menu"
echo "X) Exit"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      0) echo "0" > /sys/class/misc/touchwake/enabled && echo "TouchWake is Disabled" && sh popcorn_tw;;
      1) echo "1" > /sys/class/misc/touchwake/enabled && echo "TouchWake is enabled" && sh popcorn_tw;;
      2) sh popcorn_tw1;;
      R) sh popcorn;;
      X) exit 1;;
      *) echo "Invalid option" && sh popcorn_tw;;
     
    esac
  fi

