#!/bin/bash

OLD=$(cat /sys/module/bcmdhd/parameters/wifi_pm)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 	     Wifi Low-Latency Toggle            +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Current Setting: $OLD"
echo "1) Enable Wifi Low-Latency--default"
echo "2) Disable Wifi Low-Latency"
echo "R) Return to Main Menu"
echo "X) Exit Script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) echo "Y" > /sys/module/bcmdhd/parameters/wifi_pm && echo "Wifi Low Latency mode enabled" && sh popcorn_wll;;
      2) echo "N" > /sys/module/bcmdhd/parameters/wifi_pm && echo "Wifi Low Latency mode disabled" && sh popcorn_wll;;
      R) sh popcorn;;
      X) exit 1;;
   *) echo "Invalid option" && sh popcorn_wll;;
     
    esac
  fi

