#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+             Touch Wake Toggle/Params            +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "1) Toggle Touch Wake (0=off 1=on)"
echo "2) State Delay Time (this number should be a numerical value---default is 45000, 0=indefinate"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      0) echo "0" > /sys/class/misc/touchwake/enabled;;
      1) echo "1" > /sys/class/misc/touchwake/enabled;;
      $opt) echo "$opt" > /sys/class/misc/touchwake/delay;;
     
    esac
  fi

