#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 		Smart Reflex Toggle             +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "1) Enable SmartReflex for MPU"
echo "2) Disable SmartReflex for MPU"
echo "3) Enable SmartReflex for IVA"
echo "4) Disable SmartReflex for IVA"
echo "5) Enable SmartReflex for Core (GPU)"
echo "6) Disable SmartReflex for Core (GPU)"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
      1) echo "1" > /sys/kernel/debug/smartreflex/sr_mpu/autocomp;;
      2) echo "0" > /sys/kernel/debug/smartreflex/sr_mpu/autocomp;;
      3) echo "1" > /sys/kernel/debug/smartreflex/sr_iva/autocomp;;
      4) echo "0" > /sys/kernel/debug/smartreflex/sr_iva/autocomp;;
      5) echo "1" > /sys/kernel/debug/smartreflex/sr_core/autocomp;;
      6) echo "0" > /sys/kernel/debug/smartreflex/sr_core/autocomp;;
    esac
  fi

