#!/bin/bash

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                 +"
echo "+ 	         Gamma Offsets                     +"
echo "+                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo "Pick your offsets. Recommended values are -6 0 7"
echo "Or Press R to return to Original Color Control Script or press X to exit the script"
echo
echo
echo
echo -n "Enter option: "
read opt
if [ "$?" != "1" ]
  then
    case $opt in
    R) sh popcorn_cc;;
    X) exit 1;;
  $opt) echo "$opt" > /sys/class/misc/colorcontrol/v1_offset && echo "V1 Offsets Set at $opt" && sh popcorn_cc;;


     
    esac
  fi

